# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbfac55065ea56c3c7fd4c23a35821ba4870e5366e2be44eb6c0ad9554054beee0018a2531b6d2b08e5319b4d4ea85f8f83b20d740fcfe20b462f12fd9d38625

test:
  secret_key_base: a425d0945ac488126c2f901e89fea987ed704cfe59f8e74ccc477f23c7ecb9a1d1f6ae2d96b613ad08fdf103147f01f095a9143c4ccfdfcb7583e18bd8d3e241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
